#BANCO DSV
#spring.datasource.url=jdbc:postgresql://localhost:5432/hubsellerapp
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#Local Producao
#spring.datasource.url=jdbc:postgresql://dpg-d6kmf8ma2pns7392tqm0-a.oregon-postgres.render.com:5432/hubseller_postgresql
#spring.datasource.username=hubseller_postgresql_user
#spring.datasource.password=Ny3YqCQRMYfVWqcgWVsrBE2kpAFceaS9

#Producao
spring.datasource.url=jdbc:postgresql://dpg-d6kmf8ma2pns7392tqm0-a:5432/hubseller_postgresql
spring.datasource.username=hubseller_postgresql_user
spring.datasource.password=Ny3YqCQRMYfVWqcgWVsrBE2kpAFceaS9

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50

server.port=8080
server.servlet.context-path=/hubsellerapp-backend

api.security.token.secret=${JWT_SECRET:my-secret-key}
jwt.expiration=28800000

mercadolivre.client-id=2920348322216618
mercadolivre.client-secret=MOtA7rtbu4bMhk1uybi21EUYxxJGmgbZ
mercadolivre.redirect-uri=https://ac1a-2804-950-8103-1700-7354-69e-4446-1b7c.ngrok-free.app
mercadolivre.base-url=https://api.mercadolibre.com

imgbb.api.key=87cbf9309691653ef2cdfbfd93466459